name: Go Release CI

on:
    push:
      # run only against tags
      tags:
        - '*'

jobs:
  release:
    name: Build Go App Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: git fetch --force --tags
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - run: go version
    - uses: goreleaser/goreleaser-action@v4
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro':
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Your GoReleaser Pro key, if you are using the 'goreleaser-pro'
        # distribution:
        # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}